apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: customers
  description: Service managing all customers information
  tags:
    - springboot
    - java
spec:
  type: service
  lifecycle: production
  owner: customer-processes
